### PR TITLE
changed playall from button to href 

### PR DESCRIPTION
**Pull request by Harish321**

### CODE REVIEW

**Comment by a-c-sreedhar-reddy** [comment]
'onchange': 'this.form.submit();'})
 what does this do

**Comment by a-c-sreedhar-reddy** [comment]
how can we remove submit button

**Comment by Harish321** [comment]
"onchange = this.form.submit()" will automatically submits the form after user selected the songs.

I did that part as an experment some how if we change "Add songs(href on toolbar)" i.e when ever use clicks it it open a select window and user select the songs and it automatically submit it.

No need to open an extra page(Which is good I thought)

**Comment by a-c-sreedhar-reddy** [comment]
have u tested using it

**Comment by Harish321** [comment]
yep , why don't you  clone(or download ) my repository and pull it and see the changes and if those are valid accept the pull request and if there are errors let me know

**Pull request merged**
